import { Hero } from './components/Hero.js';
import {
  AccessibilitySection,
  ConsoleSection,
  GallerySection,
  MetadataSection,
  MethodologySection,
  NetworkSection,
  SecuritySection,
} from './components/Sections.js';
import { useReport } from './report.js';

const NAV = [
  { id: 'overview', label: 'Overview' },
  { id: 'viewports', label: 'Viewports' },
  { id: 'console', label: 'Console' },
  { id: 'network', label: 'Network' },
  { id: 'accessibility', label: 'Accessibility' },
  { id: 'security', label: 'Security' },
  { id: 'metadata', label: 'Metadata' },
  { id: 'methodology', label: 'Methodology' },
];

export function App(): JSX.Element {
  const state = useReport();

  if (state.status === 'loading') {
    return (
      <div className="shell">
        <p className="empty">Loading report…</p>
      </div>
    );
  }

  if (state.status === 'empty') {
    return (
      <div className="shell">
        <div className="placeholder">
          <p className="hero__eyebrow">VibeCheck: Automated Prototype Quality Lab</p>
          <h1 className="hero__pitch">No report published yet.</h1>
          <p>Generate the curated demo snapshot, then reload this page:</p>
          <pre className="code">npm run update:demo-snapshot</pre>
          <p className="muted">
            This builds the demo fixture, scans it across three viewports, and writes a validated
            snapshot into this viewer.
          </p>
        </div>
      </div>
    );
  }

  if (state.status === 'error') {
    return (
      <div className="shell">
        <div className="placeholder placeholder--error" role="alert">
          <p className="hero__eyebrow">VibeCheck</p>
          <h1 className="hero__pitch">This report could not be displayed.</h1>
          <p className="muted">{state.message}</p>
          <p className="muted">
            The viewer validates every report against the schema and refuses to render invalid or
            tampered data.
          </p>
        </div>
      </div>
    );
  }

  const { report } = state;

  return (
    <div className="shell">
      <nav className="sidenav" aria-label="Report sections">
        <span className="sidenav__brand">VibeCheck</span>
        <ul>
          {NAV.map((item) => (
            <li key={item.id}>
              <a href={`#${item.id}`}>{item.label}</a>
            </li>
          ))}
        </ul>
      </nav>

      <main className="content">
        <div id="overview">
          <Hero report={report} />
        </div>
        <GallerySection report={report} />
        <ConsoleSection report={report} />
        <NetworkSection report={report} />
        <AccessibilitySection report={report} />
        <SecuritySection report={report} />
        <MetadataSection report={report} />
        <MethodologySection />
        <footer className="appfoot">
          Generated by VibeCheck. All findings are observed from a real browser session.
        </footer>
      </main>
    </div>
  );
}
